services:
  - type: web
    name: technical-fest-booking
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:./ticket_booking_db;DB_CLOSE_DELAY=-1;MODE=MySQL
